name: CI
on:
  push:
    branches: [ main, bronze ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps (runtime + dev)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff==0.6.8 mypy==1.11.2 pytest==8.3.2 types-PyYAML

      - name: Lint (ruff)
        run: ruff check .

      - name: Type-check (mypy)
        run: mypy .

      - name: Test (pytest)
        run: pytest -q
